### ISSUE TITLE
Roadmap for v1.0.0 and removing preview label

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/vscode-peacock#56]
# Roadmap 

- [x] - Stabilize the menu names
- [x] - Finalize list of affected elements
- [x] - Add preferred colors list #44, #42 
- [x] - Ensure test scenarios are complete for most use cases 
- [x] - Fill in any gaps in the Readme/docs #1
- [x] - Add the ability to retain your theme's foreground color #27
- [x] - Colorize status bar item hover background #60
- [x] - Adjust activity bar badge color based on background #58 
- [x] - Refactor tests to reduce compelixty #46
- [x] - Add CI process on multiple OS platforms #30
- [x] - Add guidelines for what Peacock should affect to the Readme #59
- [x] - Remove "preview" label

**Comment by johnpapa** [comment]
I think things are looking good for a stable API. The key is not making any breaking changes.

I'll give this a few days to see if any issues arise. If not, I'll remove the preview flag and publish this as v1.0.0

**Comment by johnpapa** [comment]
released!
